# Generated by Django 5.0 on 2023-12-14 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacjent', '0003_alter_pacjent_second_name'),
        ('pracownik', '0003_alter_lekarz_pracownik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalendarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin_wizyty', models.DateTimeField(default=django.utils.timezone.now)),
                ('czy_zajety', models.CharField(blank=True, choices=[('W', 'Wolny termin'), ('Z', 'Zajęty termin')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_sali', models.IntegerField()),
                ('status', models.CharField(choices=[('Z', 'Zakończono'), ('O', 'Oczekiwanie na wizytę')], default='O', max_length=1)),
                ('kalendarz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wizyta.kalendarz')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjent.pacjent')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracownik.lekarz')),
            ],
        ),
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wystawienia', models.DateTimeField()),
                ('dawkowanie', models.CharField(max_length=255)),
                ('wizyta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizyta.wizyta')),
            ],
        ),
        migrations.CreateModel(
            name='Paragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.FloatField()),
                ('metoda_platnosci', models.CharField(choices=[('karta', 'Płatność kartą'), ('gotówka', 'Płatność gotówką')], max_length=100)),
                ('nazwa_uslugi', models.CharField(max_length=255)),
                ('data_wydania', models.DateTimeField()),
                ('wizyta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizyta.wizyta')),
            ],
        ),
    ]
