# Generated by Django 5.0 on 2023-12-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizyta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.CharField(choices=[('Zakończono', 'Zakończono'), ('Oczekiwanie na wizytę', 'Oczekiwanie na wizytę')], default='Oczekiwanie na wizytę', max_length=25),
        ),
    ]
