# Generated by Django 5.0 on 2023-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PESEL', models.IntegerField(max_length=11)),
                ('name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phone_number', models.IntegerField(max_length=9)),
            ],
        ),
    ]
