# Generated by Django 5.0 on 2023-12-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='PESEL',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
