# Generated by Django 5.0 on 2023-12-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjent', '0002_alter_pacjent_pesel_alter_pacjent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='second_name',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
