# Generated by Django 5.0 on 2023-12-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=45)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracownik.pracownik')),
            ],
        ),
    ]
