# Generated by Django 5.0 on 2023-12-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='pracownik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pracownik.pracownik'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='second_name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
