# Generated by Django 5.0 on 2023-12-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownik', '0002_alter_lekarz_pracownik_alter_pracownik_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracownik.pracownik'),
        ),
    ]
