# Generated by Django 5.0 on 2023-12-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacjent', '0003_alter_pacjent_second_name'),
        ('pracownik', '0003_alter_lekarz_pracownik'),
        ('wizyta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumentacja_medyczna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_choroby', models.TextField()),
                ('operacje', models.CharField(max_length=255)),
                ('wyniki_badan', models.TextField()),
                ('zalecenia_lekarskie', models.TextField()),
                ('lekarz_wystawiajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracownik.lekarz')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjent.pacjent')),
                ('recepta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizyta.recepta')),
            ],
        ),
    ]
